# INtellij Http client requests

GET http://localhost:8080/users
Accept: application/json

###

PUT http://localhost:8080/users
Accept: application/json

###

GET http://localhost:8080/users/1
Accept: application/json

###

PATCH http://localhost:8080/users/2
Accept: application/json
Content-Type: application/json

{
  "firstName": "trololol",
  "lastName": "trolololol"
}

###